---
- name: Configuração do servidor de banco de dados
  hosts: database

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "bugdev123"
  tasks:
    - name: Configuração dos hosts ansible
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
        - 192.168.0.104 database
        - 192.168.0.102 application
  roles:
    - roles
    - role: geerlingguy.mysql

#90Jz1NX9