- name: Stop Instance EC2 AWS
  hosts: all
  tasks:

  - name: Install boto3 and botocore with pip3 module
    pip:
      name:
      - boto
      - boto3
      - botocore==1.22.12

  - name: Stop the sandbox instances
    ec2:
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      instance_tags:
          Name: "{{ name_instance }}"
      region: "{{ region }}"
      state: running
      wait: True